accounts/urls.py
from django.urls import path 
from .views import ChatView, IndexView, NewChat, addUser, SettingsView, LeaveView 
from . import views 
 
app_name = "accounts" 
urlpatterns = [ 
    path("<int:pk>/leave", LeaveView.as_view(), name = "leave"), 
    path("settings", SettingsView.as_view(), name="settings"), 
    path("<int:pk>/messages/", ChatView.as_view(), name="messages"), 
    path("chatIndex/",IndexView.as_view(),name="chat index"), 
    path("newChat/",NewChat.as_view(),name="new chat"), 
    path("newChat/<int:pk>/addUser",addUser.as_view(),name="add user"),
    path("logout/", views.logout_view, name="logout")
] 

nea/urls.py
from django.contrib import admin 
from django.urls import path 
from django.urls import include, path 
from django.conf import settings 
from django.urls import include, path  # For django versions from 2.0 and up 
import debug_toolbar 
from django.views.generic.base import TemplateView  # new 
 
urlpatterns = [ 
    path('admin/', admin.site.urls), 
    path("accounts/", include("accounts.urls")),  
    path("users/", include("users.urls")),  
    path("accounts/", include("django.contrib.auth.urls")),  # new 
    path("__debug__/", include("debug_toolbar.urls")), 
    path("", TemplateView.as_view(template_name="home.html"), name="home"), 
]

accounts/forms.py
from typing import Any 
from django import forms 
from django.core.exceptions import ValidationError 
 
class MessageForm(forms.Form): 
    new_message = forms.CharField(label="new message:", max_length=1000) 

  
 
class NameForm(forms.Form): 
    name = forms.CharField(label="username:", max_length=100) 
 
class UsersForm(forms.Form): 
    name = forms.CharField(label="Find User:", max_length=100) 
 
class AddUserButton(forms.Form): 
   button = forms.NullBooleanField() 
 
class SettingsForm(forms.Form): 
    username = forms.CharField(label = "username:", max_length= 100) 
    email = forms.EmailField(label = "email:") 
    password = forms.CharField(label = "new password:") 
 
class RemoveChatButton(forms.Form): 
   button = forms.NullBooleanField()

templates/chats/addUser.html
{% load static %} 
<head> 
<link rel="stylesheet" href="{% static 'style.css' %}"> 
<style> 
h1 {text-align: center;} 
p {text-align: center;} 
div {text-align: center;} 
</style> 
</head> 
 
<body> 
<h1>Find User</h1> 
 
{% if i%} 
  <ul> 
  <p> 
  {{ i.username }} 
  </p> 
  <form method="POST"> 
  {% csrf_token %} 
  <input type="submit" value="add user"> 
  </form> 
  </ul> 
{%endif%} 
<form action="{% url 'accounts:add user' pk %}" method="get"> 
  <input name="q" autocomplete = "off" type="text" placeholder="Search..."> 
</form> 
<a class = "button2", href="{% url 'accounts:chat index' %}">done</a> 
</body>

templates/chats/chatIndex.html
{% load static %} 
<link rel="stylesheet" href="{% static 'style.css' %}"> 
<style> 
h1 {text-align: center;} 
p {text-align: center;} 
div {text-align: center;} 
a {text-align:center;} 
</style> 
 
<h1>CHATS!!</h1> 
{% if chat_list %} 
    <ul> 
    {% for chat in chat_list %} 
    <p> 
    <a href="{% url 'accounts:messages' chat.chatID %}">{{chat.name}}</a> 
    <a href="{% url 'accounts:leave' chat.chatID %}">Delete</a> 
    </p> 
    {% endfor %} 
     
    </ul> 
{% else %} 
    <p>No chats are available.</p> 
{% endif %} 
<br> 
<br> 
<p> 
<a class = "button", href="{% url 'home' %}">home</a> 
<a class = "button", href="{% url 'accounts:new chat' %}">new chat</a> 
</p> 

templates/chats/chatPage.html
{% load static %} 
 
<link rel="stylesheet" href="{% static 'style.css' %}"> 
 
<!DOCTYPE html> 
<h1>Messages</h1> 
<div class = myDiv> 
{% if message_list %} 
    <ul> 
    {% for m in message_list %} 
        <div class="row">  
            {% for key, value in m.items %} 
                {%if key == "timestamp"%} 
                    <font color="#786527">[{{ value }}]</font>   
                {% elif key == "user" %} 
                    <font color="#786527">{{ value }}</font> 
                {%else%} 
                    <font color="#14334e">: {{ value }}</font> 
                {%endif%} 
            {% endfor %} 
         
        </div>  
    {% endfor %} 
    </ul> 
{% else %} 
    <p>No messages are available.</p> 
{% endif %} 
 
</div> 
   
<html> 
  <body> 
    <br> 
    <div 
      class="chat__item__container" 
      id="id_chat_item_container" 
      style="font-size: 20px" 
    > 
    <br/> 
    <!--<input type="text" id="id_message_send_input" />--> 
    <form method = "POST"> 
    {% csrf_token %}  
    <input type="text" class="icon" name="new_message" autocomplete="off" maxlength="1000" required="" id="id_message_send_input"> 
    </form> 
    <button hidden type="submit" id="id_message_send_button">Send Message</button> 
     
    <br/> 
    <br/> 
    </div> 
 
    <script> 
      const chatSocket = new WebSocket("ws://" + window.location.host + "/"); 
      chatSocket.onopen = function (e){ 
        console.log("The connection was setup successfully !"); 
      }; 
      chatSocket.onclose = function (e){ 
        console.log("Something unexpected happened !"); 
      }; 
      document.querySelector("#id_message_send_input").focus(); 
      document.querySelector("#id_message_send_input").onkeyup = function (e) { 
        if (e.keyCode == 13) { 
          document.querySelector("#id_message_send_button").click(); 
        } 
      }; 
      document.querySelector("#id_message_send_button").onclick = function (e) { 
        var messageInput = document.querySelector( 
          "#id_message_send_input" 
        ).value; 
        chatSocket.send(JSON.stringify({ message: messageInput, username : "{{request.user.username}}"})); 
      }; 
      chatSocket.onmessage = function (e) { 
        const data = JSON.parse(e.data); 
        /*var div = document.createElement("div"); 
        div.innerHTML = data.username + " : " + data.message; 
        document.querySelector("#id_message_send_input").value = ""; 
        document.querySelector("#id_chat_item_container").appendChild(div);*/ 
        location.reload() 
      }; 
    </script> 
 
  </body> 
</html> 
<p> 
<a class = "button", href="{% url 'accounts:chat index' %}"> 
    <div>return</div> 
</a> 
</p> 

templates/chats/leaveChat.html
{% load static %} 
<link rel="stylesheet" href="{% static 'style.css' %}"> 
<style> 
h1 {text-align: center;} 
p {text-align: center;} 
div {text-align: center;} 
a {text-align:center;} 
</style> 
 
<body> 
<h1>Are you sure you want to delete this chat?</h1> 
<form method="POST"> 
{% csrf_token %} 
 
<input class = "button2" type="submit" value="yes"> 
</form> 
<br> 
<a href="{% url 'accounts:chat index'%}">No</a> 
</body> 

templates/chats/newChat.html
{% load static %} 
 
<head> 
<link rel="stylesheet" href="{% static 'style.css' %}"> 
<style> 
h1 {text-align: center;} 
p {text-align: center;} 
div {text-align: center;} 
</style> 
</head> 
 
<h1>New Chat?!</h1> 
<br> 
<img src="{% static 'shocked.gif' %}"> 
 
<form method = "POST"> 
{% csrf_token %}  
<input type="text" placeholder="chat name" name="name" maxlength="100" 
required="" id="id_name"> 
<p> 
<input type = "submit" value = "create and add users">  
<button> 
<a href="{% url 'accounts:chat index' %}">return</a> 
</button> 
</p>

templates/chats/settings.html
{% load static %} 
<style> 
h1 {text-align: center;} 
h2 {text-align: center;} 
p {text-align: center;} 
div {text-align: center;} 
</style> 
 
 
{%if error %} 
    <script>alert('email already in use');</script>  
{%endif%} 
<head> 
<h1>{{user.email}}</h1> 
<h1>Change Settings</h1> 
<p>{{text}}</p> 
<form method = "POST"> 
{% csrf_token %}  
{{form.as_ul}} 
<input type="submit" value="Save"> 
</form> 
</head> 