accounts/urls.py
from django.urls import path 
from .views import ChatView, IndexView, NewChat, addUser, SettingsView, LeaveView 
from . import views 
 
app_name = "accounts" 
urlpatterns = [ 
    path("<int:pk>/leave", LeaveView.as_view(), name = "leave"), 
    path("settings", SettingsView.as_view(), name="settings"), 
    path("<int:pk>/messages/", ChatView.as_view(), name="messages"), 
    path("chatIndex/",IndexView.as_view(),name="chat index"), 
    path("newChat/",NewChat.as_view(),name="new chat"), 
    path("newChat/<int:pk>/addUser",addUser.as_view(),name="add user"),
    path("logout/", views.logout_view, name="logout")
] 

nea/urls.py
from django.contrib import admin 
from django.urls import path 
from django.urls import include, path 
from django.conf import settings 
from django.urls import include, path  # For django versions from 2.0 and up 
import debug_toolbar 
from django.views.generic.base import TemplateView  # new 
 
urlpatterns = [ 
    path('admin/', admin.site.urls), 
    path("accounts/", include("accounts.urls")),  
    path("users/", include("users.urls")),  
    path("accounts/", include("django.contrib.auth.urls")),  # new 
    path("__debug__/", include("debug_toolbar.urls")), 
    path("", TemplateView.as_view(template_name="home.html"), name="home"), 
]

users/urls.py
from django.urls import path 
from .views import signup 
from . import views 
 
app_name = "users" 
urlpatterns = [ 
    path("signup/", signup, name="signup"), 
]

templates/base.html
<!DOCTYPE html> 
<html> 
<head> 
  <meta charset="utf-8"> 
  <title>{% block title %}bruh text{% endblock %}</title> 
</head> 
<body> 
  <main> 
    {% block content %} 
    {% endblock %} 
  </main> 
</body> 
</html>

templates/home.html
{% extends "base.html" %} 
{% block content %} 
{% load static %} 
 
<head> 
<link rel="stylesheet" href="{% static 'style.css' %}"> 
<style> 
h1 {text-align: center;} 
h2 {text-align: center;} 
p {text-align: center;} 
div {text-align: center;} 
</style> 
</head> 
 
<body> 
<h1>Haiiii!</h1> 
{% if user.is_authenticated %} 
  <h2>Hi {{ user.username }}!</h2> 
  <a class = "button", href="{% url 'accounts:chat index' %}"> 
    <div>chats</div> 
  </a> 
  <p></p> 
  <a class = "button", href="{% url 'logout' %}"> 
    <div>logout</div> 
  </a> 
  <a class = "button", href="{% url 'accounts:settings' %}"> 
    <div>settings</div> 
  </a> 
 
 
   
{% else %} 
  <p>You are not logged in</p> 
  <a class = "button2", href="{% url 'login' %}">Log In</a> 
  <a class = "button2", href="{% url 'users:signup' %}">Sign Up</a> 
{% endif %} 
{% endblock %} 
</body>